### ISSUE TITLE
Installation/run errors.

### ISSUE THREAD

**Issue by MariasStory** [vladmandic/pigallery#2]
Hi @vladmandic,
The project sounds very interesting.
Thanks for open sourcing, I'll try to contribute ;-)

I was trying to install and got the error that was fixed by commenting line 99 and 100 from setup.js.

Maybe you can check the following error: Cannot find module '@vladmandic/pilogger'?

Error in setup.js:
```
./setup.js
Starting Setup
@vladmandic/pigallery server v2.2.2
Platform=linux Arch=x64 Node=v15.0.1
Project dependencies
 production: 18
 development: 8
 optional: 0
NPM install production modules completed in 19,243ms
NPM install development modules completed in 8,695ms
NPM install optional modules completed in 4,233ms
NCU force upgrade modules
NPM update modules completed in 22,279ms
NPM deduplicate modules completed in 7,619ms
NPM prune unused modules completed in 2,192ms
Deleting module samples completed in 72ms
NPM outdated check completed in 3,020ms
NPM indirect outdated modules: 45
NPM list full completed in 1,127ms
pigallery/node_modules/npm-check-updates/lib/npm-check-updates.js:353
  throw err
  ^

TypeError: Cannot read property 'metadata' of undefined
    at main (/home/myname/Downloads/pigallery/setup.js:99:32)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)

```
------

Error during a first run attempt:
```
npm start

> @vladmandic/pigallery@2.2.2 start pigallery
> node --unhandled-rejections=strict --pending-deprecation server/pigallery.js

node:internal/modules/cjs/loader:903
  throw err;
  ^

Error: Cannot find module '@vladmandic/pilogger'
Require stack:
- pigallery/server/pigallery.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:900:15)
    at Function.Module._load (node:internal/modules/cjs/loader:745:27)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (/home/myname/Downloads/pigallery/server/pigallery.js:3:13)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/myname/Downloads/pigallery/server/pigallery.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @vladmandic/pigallery@2.2.2 start: `node --unhandled-rejections=strict --pending-deprecation server/pigallery.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @vladmandic/pigallery@2.2.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/myname/.npm/_logs/2020-11-17T20_11_10_070Z-debug.log

```

**Comment by vladmandic** [comment]
thanks for reporting - the project is running on my system, but i'm yet to run end-to-end install and update docs (which haven't been updated in months).

i also need to find a way to distribute models are they are too big to distribute using github.

**Comment by MariasStory** [comment]
I see people use BaiduDrive and Dropbox for the models.

**Comment by vladmandic** [comment]
absolutely, it's all workable, just haven't done it yet.

one reason is that i'm working with tfjs team to fix issues with execution of some models before i lock-in which models i intent to use as final. right now i have 20+ models in testing and that needs to be narrowed down.

for example, object detection based on mobilenetv2 is decent, but efficientdet is far better - but it's only compatible since a week ago. and centernet was fixed yesterday.

still have two outstanding and then i can work on packaging and end-to-end install.

**Comment by boboche** [comment]
Same here, was browsing around, found this project that looks promising and on a clean Ubuntu VM I get this
(...)
NPM list full completed in 2,219ms
(node:9273) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'metadata' of undefined
    at main (/home/test/pigallery-2.1/setup.js:99:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:9273) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9273) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by boboche** [comment]
Commented out what was causing the error, further down npm start, same thing.  Ubuntu 20.04 clean install.   did apt-get install nodejs and npm before.

Results written to setup.json
root@test-VirtualBox:/home/test/pigallery-2.1# npm start

> @vladmandic/pigallery@2.2.8 start /home/test/pigallery-2.1
> node --unhandled-rejections=strict --pending-deprecation --trace-deprecation server/pigallery.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '@vladmandic/pilogger'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/test/pigallery-2.1/server/pigallery.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @vladmandic/pigallery@2.2.8 start: `node --unhandled-rejections=strict --pending-deprecation --trace-deprecation server/pigallery.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @vladmandic/pigallery@2.2.8 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-14T21_02_55_528Z-debug.log

**Comment by vladmandic** [comment]
i'd redo the packaging and installer this week, it's been long overdue...

**Comment by vladmandic** [comment]
i've just published v3.0 with completely redone install procedure and updated docs

**Comment by vladmandic** [comment]
closing the issue as new version should resolve all installation issues.

**Comment by boboche** [comment]
Still getting the error, Setup is fine, barks on npm start.

Ubuntu Server 20.04.1 LTS Fresh install first thing I ran after installing nodeJS (current, not from ubuntu default which was 10.x at the time of this writing and I was suspecting it was too old)

test@test:~/pigallery$ ./setup.js
Starting Setup
@vladmandic/pigallery server v3.0.3
Platform=linux Arch=x64 Node=v15.9.0
Project dependencies
 production: 19
 development: 8
 optional: 0
NPM install production modules completed in 1,467ms
NPM install development modules completed in 1,502ms
NPM update modules completed in 9,816ms
NPM deduplicate modules completed in 2,410ms
NPM prune unused modules completed in 1,329ms
NPM audit modules completed in 1,317ms
Deleting module samples completed in 21ms
NPM outdated check completed in 995ms
NPM indirect outdated modules: 4
NPM list full completed in 621ms


test@test:~/pigallery$ npm start

/home/test/pigallery/setup.js:102
  const meta = npm.prune.audit.metadata;
                               ^
TypeError: Cannot read property 'metadata' of undefined
    at main (/home/test/pigallery/setup.js:102:32)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
> @vladmandic/pigallery@3.0.3 start
> node --unhandled-rejections=strict --pending-deprecation --trace-deprecation server/pigallery.js
2021-02-18 22:12:40 ERROR:  Configuration file config.json cannot be read
2021-02-18 22:12:40 INFO:  @vladmandic/pigallery version 3.0.3
2021-02-18 22:12:40 INFO:  User: test Platform: linux Arch: x64 Node: v15.9.0
2021-02-18 22:12:40 STATE:  Application log: /home/test/pigallery/pigallery.log
2021-02-18 22:12:40 INFO:  Authentication required: undefined
2021-02-18 22:12:40 INFO:  Media root: undefined
2021-02-18 22:12:40 INFO:  Allowed image file types: undefined
2021-02-18 22:12:40 DATA:  Build sources: [ 'client/compare/compare.js', 'client/index/index.js', 'client/process/process.js', 'client/prototype/prototype.js', 'client/video/video.js', [length]: 5 ] [ 'client/index/worker.js', 'client/index/pwa-serviceworker.js', [length]: 2 ]
2021-02-18 22:12:40 ERROR:  Cannot open application log pigallery.log: EACCES
node:fs:497
  handleErrorFromBinding(ctx);
  ^
Error: EACCES: permission denied, open '/home/test/pigallery/CHANGELOG.md'
    at Object.openSync (node:fs:497:3)
    at Object.writeFileSync (node:fs:1521:35)
    at Object.update (/home/test/pigallery/server/changelog.js:30:6)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/home/test/pigallery/CHANGELOG.md'
}
npm ERR! code 1
npm ERR! path /home/test/pigallery
npm ERR! command failed
npm ERR! command sh -c node --unhandled-rejections=strict --pending-deprecation --trace-deprecation server/pigallery.js
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/test/.npm/_logs/2021-02-18T22_12_40_830Z-debug.log

**Comment by vladmandic** [comment]
ah, on a clean system there is never anything to prune so audit object was empty and setup failed before it could create default configuration.  
as a last setup step, if `config.json` does not exist it should ask you for a default user/password and create `config.json` for you  
(if valid configuration is found, it will not overwrite it)  

hopefully, that's fixed in new 3.0.4 that i've just published.  

but EACCESS errors for log file creation are strange - does your user have full write priviledges to pigallery root folder?

(reopening issue until its resolved)

**Comment by boboche** [comment]
Yeah scratch the EACCESS part.

I figured the nodeJS version shipped with ubuntu (10) could be problematic so I did

curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash -
sudo apt-get install -y nodejs

before running the install.   Waiting for the fix, will try again. ;)

**Comment by vladmandic** [comment]
> Waiting for the fix, will try again. ;)

If you mean PiGallery `setup.js` fix, it's already posted.

Unrelated, for NodeJS installations and version management, I really like `NVM`: <https://github.com/nvm-sh/nvm>

**Comment by boboche** [comment]
Oh.  Well I must be doing something horribly wrong then.

I'm not a git pro, I rm -rf pigallery and re-ran git clone --depth 1 etc...  sudo npm start got this

(all before okay)...
NPM list full completed in 1,308ms
Cannor analyze dependencies
/home/test/pigallery/setup.js:104
  process.stdout.write(`Total dependencies: production=${meta.dependencies || 'N/A'} development=${meta.devDependencies || 'N/A'} optional=${meta.optionalDependencies || 'N/A'}\n`);
                                                              ^

TypeError: Cannot read property 'dependencies' of undefined
    at main (/home/test/pigallery/setup.js:104:63)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
npm ERR! code 1
npm ERR! path /home/test/pigallery
npm ERR! command failed
npm ERR! command sh -c node ./setup.js

**Comment by vladmandic** [comment]
you're not doing anything wrong.  

i don't understand (and cannot reproduce) why would a simple command such as  
`npm prune --json`  
not return stats on your system. can you try to execute it manually and paste the output?  

on the other hand, package stats are just stats and not critical for setup to complete.
i just added code to report warning and continue with setup - new version is published.

btw, not related, but why are you running with `sudo npm ...`?  
pigallery is design to run with minimum required privileges, it doesn't require root access. basically, you should run `./setup.js` and then `npm start` as the same user that owns the pigallery root folder (which by default is same user that performed `git clone` operation).

**Comment by boboche** [comment]
Was writing the prune output and all while re-installing and surprise,  it seems to work okay now.

Your sudo question made me wonder if I checked out with sudo and all in the last run after your repackaging...might have been already working without the last change. My bad.   All good now! Can finally play around with it :)

Thanks!

**Comment by vladmandic** [comment]
glad that setup now works, let's see how it goes from here :)

and yes, it could be that you checked out repository with sudo, so when started normal user did not have write privileges - thus `EACCESS` errors.

**Comment by vladmandic** [comment]
closing as resolved

**Comment by NolanCassidy** [comment]
@vladmandic It appears to be happening again. I have tried node 16 and node 18 on windows 10 and ubuntu 22 and I am getting the error Cannot find module '@vladmandic/pilogger'

I am just trying to run the webcam.html demo on @vladmandic/face-api

**Comment by vladmandic** [comment]
@NolanCassidy that's a different root cause and for a completely different repository
(and in general its never a good idea to post on a thread that has been closed for over two years)

can you open a an issue at <https://github.com/vladmandic/face-api/issues> and i'll reply there.
